'''
Step 1: Start by defining the grammar rules of the language that the parser will be parsing.
Step 2: Create a lexical analyzer (also known as a lexer or scanner) that will read in the input code and tokenize it according to the grammar rules.
Step 3: Create a parser that will use the tokens generated by the lexer to construct a parse tree. The parse tree represents the structural relationship between the different parts of the code.
Step 4: Use a stack-based approach to parse the input code. The parser will push the tokens onto the stack and use a set of rules to determine how to reduce the input code into a parse tree.
Step 5: Implement error handling mechanisms to detect and recover from syntax errors in the input code.
Step 6: Once the parse tree has been constructed, the parser may do additional processing to generate intermediate code or perform semantic analysis.
Step 7: Finally, the parser may output the result of its processing in some form, such as machine code or a high-level representation of the input code.
'''

def generate_AST(string):
  number_symbols = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '.', '-']
  ind = 1 
  arr_to_return = []
  while ind < len(string):
    char = string[ind] 
    if char == "(":
      open_cnt = 1 
      closed_cnt = 0
      sub_str = "("
      for c in string[ind + 1:]: 
        if c == "(": open_cnt += 1
        if c == ")": closed_cnt += 1
        sub_str += c 
        if open_cnt == closed_cnt: break
      arr_to_return.append(generate_AST(sub_str)) 
      ind += len(sub_str)
    elif char == " " or char == ")":
      ind += 1
    else:
      stop_ind = string.find(" ", ind)
      if stop_ind == -1:
        stop_ind = string.find(")", ind) 
      s = string[ind:stop_ind]
      if all(x in number_symbols for x in list(s)):
        if s.find('-', 1) == -1:
          num = float(s)
          arr_to_return.append(num)
      else:
        arr_to_return.append(s)
      ind = stop_ind + 1 
  return arr_to_return


if __name__ == "__main__":
    ip = "(first (list -1.5 (+ 2 3) 9))" # lisp
    print("Input(LISP):", ip)
    print("Output (AST):", generate_AST(ip))
